# Generated by Django 5.0.7 on 2024-07-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("mlflow_run_id", models.CharField(max_length=100, unique=True)),
                ("accuracy", models.FloatField(default=0.0)),
                ("model_type", models.CharField(default="unspecified", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PredictionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=100)),
                ("input_data", models.JSONField()),
                ("prediction", models.JSONField()),
                ("response_time", models.FloatField()),
                ("model_type", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
