# Generated by Django 5.0.7 on 2024-07-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_modelversion_model_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictionlog",
            name="model_type",
            field=models.CharField(max_length=150),
        ),
    ]
