artifact_location: /Users/jyotiprakashdey/Documents/Python_projects/AmlABFlow/http/:127.0.0.1:5000/0
creation_time: 1721402551775
experiment_id: '0'
last_update_time: 1721402551775
lifecycle_stage: active
name: Default
